global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

rule_files:
  - 'prometheus.rules.yaml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']

#################
# Node Exporter #
#################

  - job_name: 'node-exporter'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['node-exporter:9100']

#####################
# Cadvisor Exporter #
#####################

  - job_name: 'cadvisor'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['cadvisor:8080']
